### PR TITLE
test add denny

### PR DESCRIPTION
**Pull request by almondyoung**

### CODE REVIEW

**Comment by almondyoung** [comment]
Script Output:
  ```
  
  ```

**Comment by almondyoung** [comment]
Script Output:
  ```
  Validation failed for folder 'bazarr': name {v2 bazarr 0.1.0} invalid in Chart.yaml in chart '%!s(MISSING)', must same
  ```

**Comment by almondyoung** [comment]
test valid output:
  ```
  Validation failed for folder 'bazarr': version in app.cfg v0.1, version in Chart.yaml 0.1.0 in chart 'bazarr', must same
  ```

**Comment by almondyoung** [comment]
test valid output:
  ```
  Folder validation successful!
  ```

**Comment by almondyoung** [comment]
test valid output:
  ```
  Folder validation successful!
  ```

**Comment by almondyoung** [comment]
test valid output:
  ```
  Validation failed for folder 'bazarr': version in app.cfg 0.1.1, version in Chart.yaml 0.1.0 in chart 'bazarr', must same
  ```

**Comment by almondyoung** [comment]
test valid output:
  ```
  Validation failed for folder 'bazarr': version in app.cfg 0.1.1, version in Chart.yaml 0.1.0 in chart 'bazarr', must same
  ```

**Comment by almondyoung** [comment]
test valid output:
  ```
  Validation failed for folder 'bazarr': version in app.cfg 0.1.1, version in Chart.yaml 0.1.0 in chart 'bazarr', must same
  ```

**Comment by almondyoung** [comment]
test valid output:
  ```
  Validation failed for folder 'bazarr': version in app.cfg 0.1.2, version in Chart.yaml 0.1.0 in chart 'bazarr', must same
  ```

**Comment by almondyoung** [comment]
test valid output:
  ```
  Validation failed for folder 'bazarr': version in app.cfg 0.1.2, version in Chart.yaml 0.1.0 in chart 'bazarr', must same
  ```

**Comment by almondyoung** [comment]
test valid output:
  ```
  Validation failed for folder 'bazarr': version in app.cfg 0.1.1, version in Chart.yaml 0.1.0 in chart 'bazarr', must same
  ```

**Comment by almondyoung** [comment]
test valid output:
  ```
  Validation failed for folder 'bazarr': version in app.cfg 0.1.2, version in Chart.yaml 0.1.0 in chart 'bazarr', must same
  ```

**Comment by almondyoung** [comment]
test valid output:
  ```
  Validation failed for folder 'bazarr': version in app.cfg 0.1.1, version in Chart.yaml 0.1.0 in chart 'bazarr', must same
  ```

**Comment by almondyoung** [comment]
test valid output:
  ```
  Validation failed for folder 'bazarr': version in app.cfg 0.1.2, version in Chart.yaml 0.1.0 in chart 'bazarr', must same
  ```

**Comment by almondyoung** [comment]
test valid output:
  ```
  Validation failed for folder 'bazarr': version in app.cfg 0.1.2, version in Chart.yaml 0.1.0 in chart 'bazarr', must same
  ```

**Comment by almondyoung** [comment]
test valid output:
  ```
  Validation failed for folder 'bazarr': version in app.cfg 0.1.2, version in Chart.yaml 0.1.0 in chart 'bazarr', must same
  ```

**Comment by almondyoung** [comment]
test valid output:
  ```
  Folder validation successful!
  ```

**Comment by almondyoung** [comment]
test valid output:
  ```
  Folder validation successful!
  ```

**Review by TShentu — COMMENTED** [review]
Test Comment

**Pull request merged**
